/****************************************************************************
**
**This file was generated by the author
**
**Marcelo Teixeira Silveira, E-FOTO 2005
****************************************************************************/


#ifndef Rectifier_h
#define Rectifier_h

#include <QtGui/QColor>

class Image;

class Rectifier
{
public:
    Rectifier(Image *o, Image *r, int intp);
    Image *original, *retificada;
    int interpolacao;

public:
    void afimGeral(int modo);
    void afimIsogonal();
    void linearDireta();
    void projetiva();
    QRgb achaCor(float x, float y);
    float df(float x);
    int acertaPixel(int cor);

protected:

private:
};

#endif // Rectifier_h
